name: HMI_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - numpy=1.23.5
  - astropy=5.1
  - scipy=1.9.3
  - pywavelets=1.4.1
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - ipython=8.7.0
  - pandas=1.5.2
  - cudnn=8.1.0
  - cudatoolkit=11.2
  - pip=22.3.1
  - pip:
    - notebook==6.5.2
    - tensorflow==2.11.0
